csci-499-fa24/Team6

- server/db.js
- server/package.json
- server/server.js
- Established connection between backend and database.
- Configured database credentials and connection settings.
- Ensured connection is properly initialized and tested.
> Backend: Connect Database to the code-base

- client/app/components/navbar.js
- client/app/recipe/home.ejs
- client/app/recipe/page.js
- client/app/recipe/recipe.js
- client/package-lock.json
- client/package.json
Testing API with a dummy database on the Recipe Page
Able to print recipes based on the ingredients we have in a dummy database for now with used ingredients from the database, missing ingredients for the recipe, instructions, and their macros
Recipe directory in the app directory added recipe.js, edited page.js in recipe directory and edited navbar.js
Fix some errors that are occurring on the page
Yes
> Recipe api working with a dummy database

- client/app/components/customComponents
- client/app/login/page.js
- client/app/register/page.js
- client/app/register/register.module.css
29-Registration page frontend
Finished the first step of registration's front end
- Defined the foundational styles for registration page
- Finished the front end for the first section of registration (basic user info)
- Started on second part of registration page (adding ingredients)
- Moved some custom MUI styling to a new custom components folder
- Finish the ingredients page
- Begin the allergy page
- Begin the nutritional benefits page
- Connect the page to the backend
None
> 29-Registration page frontend

- client/app/components/navbar.js
- client/app/components/navbar.module.css
- client/app/discover/page.js
- client/app/login/page.js
- client/app/register/page.js
- client/app/register/regStep1.js
- client/app/register/regStep4.js
- server/email.js
- server/package-lock.json
- server/package.json
- server/server.js
- Log in Route
- Register Route
- Implemented login API route (/api/login) with validation, JWT token generation, and password hashing
- Implemented register API route (/api/register) with validation, JWT token generation, and password hashing
- Added logout button
- token storage
**Whats left to do?**
- forgot password (stretch)
> Implement Sign In, Sign Up, and Logout with Token Management

- client/app/recipe/RecipePage.module.css
- client/app/recipe/[id]/page.js
- client/app/recipe/recipe.js
- client/package-lock.json
- client/package.json
Hyperlinks for the recipe page, formatting the recipe page into a grid like display, when clicking on the links you are sent to a http://localhost:3000/recipe/[id] to get all the information on the recipe
This code adds a dynamic recipe page that allows users to view recipe details based on their selected ingredients, fetched via the Spoonacular API, with clickable recipe cards that link to individual recipe pages. It includes detailed information like used and missing ingredients, instructions, and nutritional data, enhancing the user experience for exploring recipe options.
New folder for the recipe id, changes to recipe.js, new .css file
Implement with the actually database, and users
**Testing …
> Added hyperlinks into the recipe page with dynamic routing and API integration

- client/app/discover/page.js
- server/email.js
- Updated API path to render site link
- Uncommented out email code 
- Just changed one line and uncommented someone's email code that i previously commented for testing 
- Updated path
> Updated URL Path

- server/server.js
- Added COR middleware to fix server issue
- Added COR middleware to fix server issue
- Updated server.js with COR options
> Added COR Middleware

- client/app/pantry/IngredientInput.js
- client/app/pantry/IngredientList.js
- client/app/pantry/page.js
- server/ingredient/ingredient.js
Add route for removing and modifying ingredient amounts in the user_ingredient table.
- Remove Ingredient #46
- Modify Ingredient Amount #45
This feature adds two key functionalities to manage ingredients in the user_ingredient table:
- Remove Ingredient: Allows users to remove an ingredient from their list.
- Modify Ingredient Amount: Allows users to modify the amount of an existing ingredient.
- A new API route to remove an ingredient from the user_ingredient table.
- A new API route to modify the amount of an ingredient in the user_ingredient table.
Error handling and validation:
- Check if the ingredient exists before attempting to delete or modify.
- Return appropriate success/error messages based on the operation …
> Add route for modifying ingredient amounts

- client/app/discover/page.js
- server/server.js
- Replaced localhost links with production URLs.
- Updated API calls to use deployed server URLs.
- Changed URLs in login, registration, and API requests.
**What's left to do?:**
- Final testing on the deployed site.
- Local testing done.
> Updated Deployed Links

- client/app/components/customComponents
- client/app/components/navbar.js
- client/app/components/navbar.module.css
- client/app/login/login.module.css
- client/app/login/page.js
- client/app/register/regStep1.js
- client/app/register/register.module.css
Fixing margins in registration page
nothing
> fixing margins

- client/app/recipe/recipe.js
number of recipes somewhat effected the formatting of the instructions dont do 2, 3 recipes called minimum
> number of recipes displayed to fix error

- .github/workflow/ci.yaml
- client/app/components/navbar.js
- server/email.test.js
- server/package-lock.json
Coverage Report + Test if login info is correct
workflow + email.test.js file
Add more test functions
> Test coverage

- client/app/pantry/IngredientInput.js
- client/app/pantry/NutritionInput.js
- client/app/pantry/pantry.module.css
Fixing pantry front end
Updating pantry-ingredients front end
Just added consistent styling to the text inputs
> Updating pantry-ingredient frontend

- client/app/recipe/[id]/page.js
Hyperlinks
Updated so it uses database instead of dummy data
> database in now connected to recipe page

- client/app/pantry/NutritionInput.js
- client/app/pantry/pantry.module.css
50 - Pantry front end
Added the visual section to the nutrition tracker that displays daily nutrition progress
Added the visual progress to each nutritional item 
Added styling to each item
Connect to backend, make the progress value be determined on users data
> Adding visual section of nutrition in pantry

- client/app/discover/DiscoverPage.module.css
- client/app/discover/[id]/RecipeDetailPage.module.css
- client/app/discover/[id]/page.js
- client/app/discover/page.js
- client/package-lock.json
- client/package.json
- server/discover/discoverPage.js
- server/server.js
Add authentication to the Discover page and implement dynamic recipe detail route.
- Added user authentication to the Discover page using token verification.
- Updated CORS settings to handle both local and Render environments.
- Implemented dynamic routing for recipe details based on recipe IDs.
- Authentication logic for the Discover page.
- Dynamic route for `/discover/[id]` to display individual recipe details.
- Pagination and filter functionality on the Discover page.
**What's left to do?:**
- Final CSS styling for the Discover and recipe details pages.
- Verified authentication works.
- Tested navigation to the recipe detail page from the Discover page.
> Dynamic recipe detail route and front end

- client/app/recipe/recipe.js
- server/package-lock.json
Recipe page front end
Fixing function to retrieve user ingredients
> fixing fetchUserIngredients in recipes

- client/app/plan/page.js
- server/nutrition/nutritionGet.js
**Issue / Feature:** render deployment
**Description:** local storage issue
**What's in this change?:** put local storage in use effect
> local storage issue

- client/app/components/navbar.js
- client/app/components/navbar.module.css
- client/app/discover/DiscoverPage.module.css
- client/app/discover/page.js
- server/discover/discoverPage.js
**Issue / Feature:**  
Fix search functionality, pagination, and button styles
**Description:**  
Implemented search functionality using Spoonacular's complex search API, fixed pagination issues, and aligned the search and login/logout buttons with consistent styling.
**What's in this change?:**  
- Integrated Spoonacular's complex search API  
- Fixed pagination to ensure unique results per page  
- Adjusted search button styling to match "Get Started" button  
- Updated login/logout button with rounded borders and hover effect
**What's left to do?:**  
Nothing right now
**Testing changes:**  
- Verified search functionality (searches only on button click)  
- Tested pagination across multiple pages for consistency  
- Ensured button hover and click interactions work as expected
> Added search functionality and fixed styling

- client/app/pantry/NutritionInput.js
- server/nutrition/nutritionGet.js
- server/nutrition/nutritionUpdate.js
- server/server.js
**Issue / Feature:** Nutritional Tracker
**Description:** Connected the User's goals with their meal plan for the day
**What's in this change?:** Added functionality to the form in the nutrition page and dynamically change the circles based on users goals.
**Whats left to do?:** enhance visuals
> connected nutritional goals to meal plan

- client/app/pantry/IngredientList.js
Adding CustomDropdown to custom components.
We also modify the CustomTextField import path to accommodate new imports.
Imported CustomDropdown from customComponents.js.
> Fix import

- client/app/components/navbar.module.css
- client/app/pantry/NutritionInput.js
- client/app/pantry/pantry.module.css
- server/nutrition/nutritionGet.js
Fixing formatting in nutritional input
Added unique colors back to nutrition
Fixed page formatting
> Adding back nutritional input section

- client/app/account/NutritionInput.js
- client/app/account/[id]/page.js
- client/app/discover/[id]/page.js
- server/nutrition/nutritionGet.js
- server/nutrition/nutritionUpdate.js
- server/plan/planAdd.js
- server/plan/planGet.js
**Issue / Feature:** Refactoring changes
**Description:** Made adjustments to Account section to work better with the new setup
**What's in this change?:** Fixed issues related to saving nutritional goals, changed endpoint to handle batch api calls instead of individual, adjusted daily nutrition handling using the new database table
**Whats left to do?:** Write code to update the database table so all columns except user_id are set to 0 at the start of each day
**Testing changes:** N/A
> refactored for new setup

- client/app/recipe/RecipePage.module.css
- client/app/recipe/[id]/page.js
- client/app/recipe/recipe.js
Recipe now has more recipes in it
Updated the Recipe.js and css for formatting and displaying more recipes
Recipe.js and css for it
Thresholds for recipe matching, search
> Updated Recipe.js and css

- client/app/discover/page.js
- server/discover/discoverPage.js
Added allergen filtering to discover page
Added dropdown filter to exclude recipes based on user's saved allergens
- Users can now filter out recipes containing their saved allergens
- Allergen options come from user's saved allergens in account settings
- Integrates with existing Spoonacular API filtering
- Added allergen dropdown to discover page filters
- Updated backend to handle allergen filtering
- Frontend changes to manage allergen state
- Add allergen filtering to recipe recommendation page
> Dynamic Allergen Filtering

- client/app/recipe/[id]/page.js
bug
fix bug on recipe hyperlink
N/A
> fix bug on recipe page where we don't have any detail on the recipe

- client/app/account/NutritionInput.js
- client/app/recipe/RecipePage.module.css
- server/plan/planAdd.js
Bug: nutrition not being updated after recipe being added to recipe history
Removed an extra comma
> removing an extra comma preventing user nutrition from being updated

- client/app/account/Profile.js
- client/app/account/page.js
Creating profile.js within account
> adding profile file

- client/app/account/EditableField.js
- client/app/account/Settings.js
- client/app/account/Settings.module.css
- server/server.js
- server/user/userUpdate.js
**Issue / Feature:**  
Add functionality to update user email from the settings page and display a success message on save.
**Description:**  
This update allows users to change their email on the settings page. After a successful save, a "Saved Successfully ✓" message appears in green, replacing the save button briefly to confirm the change visually.
**What's in this change?:**  
- Backend endpoint to handle email updates with proper authentication
- Console log to display updated user details (user ID, previous email, name, phone)
- Frontend logic to call the new API and show a success message after saving
- Minor styling updates for success message display
**What's left to do?:**  
No further steps for this feature. Will work on backend feature for updating password and phone number …
> Backend functionality for user email update

- client/app/recipe/[id]/page.js
- client/package-lock.json
- client/package.json
- Ticket #120  
- Allow users to download a PDF of the recipe they want to save.
- Modified `client/app/recipe/[id]/page.js` and created a new `generatePDF` function which builds a PDF with the recipe's title, ingredients, missing ingredients, and steps when the download buttton is clicked.
- Downloaded new npm package called `jsPDF`
**What's left to do?:**
- Nothing, this feature is complete.
- See coverage report below
- Tested different recipes to check if all the correct data is appearing on the PDF and that none of the text is being cut off at the end of the line.
Example PDF:
[Crawfish Etouffee, …
> Recipe PDF Feature

- client/app/discover/[id]/page.js
- client/app/recipe/[id]/page.js
- server/discover/autoRemove.js
- server/server.js
**Issue / Feature:** Auto remove ingredients from pantry
**Description:** When the user clicks that they cooked/made something, all the ingredients from the recipe that are in the users pantry automatically get removed
**What's in this change?:** Added a new route in server to handle the removal of the ingredients from the pantry
**Whats left to do?:** Decide how to handle units/conversions
**Testing changes:** N/A
> auto remove ingredients from pantry

- server/discover/autoRemove.js
- server/plan/planAdd.js
**Issue / Feature:** Cooked Recipe
**Description:** Edited functionality of cooking recipes
**What's in this change?:** The user can now cook the same recipe multiple times and the user nutrition will get updated accordingly
> Userpantry

- client/app/account/Settings.js
- client/app/account/Settings.module.css
- server/email_noti/email.js
- server/user/user.js
**Issue / Feature:**  
Add a complete email notification system, including automatic subscription for new users, web notifications and confirmation emails for unsubscribing.
**Description:**  
This PR introduces a robust email notification feature that automatically subscribes new users to email notifications upon registration, displays a web notification when users unsubscribe, and sends a detailed unsubscription confirmation email with the PantryPal logo and tailored styling. These updates improve the user experience, providing clear feedback and a professional touch to our communications.
**What's in this change?:**  
- **Auto-Subscription for New Users**: New users are automatically signed up for email notifications, with checkboxes pre-checked on the settings page for easy …
> Implement Email Notification System with Web Notification and Auto-Subscription for New Users

- client/app/recipe/RecipePage.module.css
- client/app/recipe/[id]/RecipeDetail.module.css
- client/app/recipe/[id]/page.js
- client/app/recipe/recipe.js
Recipe page and ID page
Added search bar and fixed the formatting on the ID page for the ingredients 
Search bar and formatting issues
The search bar isn't outputting anything right now, will work on it
> Search bar to recipes page and updates to id page

- client/app/2FA/2FA.js
- client/app/2FA/2FA.module.css
- client/app/2FA/page.js
- client/app/account/Settings.js
- client/app/account/page.js
- client/app/login/page.js
- server/email_noti/2fa.js
- server/email_noti/email.js
- server/server.js
- server/user/user.js
**Issue / Feature**  
Implement Two-Factor Authentication (2FA) to enhance account security by requiring users to enter a verification code received via email upon login.
**Description**  
This PR introduces a comprehensive 2FA system that requires users to verify their login with a 6-character alphanumeric code sent to their email. If enabled, users must input this code upon login, ensuring added security.
**What's in this change?**
1. 2FA Checkbox on Settings Page  
- Users can enable or disable 2FA by checking a box in the "Privacy & Security" tab on the settings page.
- Enabling 2FA displays a notification popup confirming the status change.
- The checkbox state is persistent, meaning the setting remains active or inactive across sessions.
2. Login Flow with 2FA Requirement 
- Upon …
> Added Two Factor Authentication

- server/discover/autoRemove.js
- server/tests/2fa.test.js
- server/tests/autoRemove.test.js
- server/tests/favorites.test.js
- server/tests/ingridient.test.js
- server/tests/planAdd.test.js
- server/tests/user.test.js
- server/user/user.js
**Issue / Feature:** Improved test coverage for several files in `server` directory.
**Description:** 
Enhanced unit tests to cover previously untested lines and error handling, focusing on files with lower coverage.
- Added tests for `user.js`, `autoRemove.js`, `favorites.js`, `ingredient.js`, `ingredientRemove.js`, `ingredientUpdate.js`, `user_ingredient.js`, `favorites.js`, and `planAdd.js`.
- Included `try/catch` blocks and `res.status().json()` handling to ensure consistent error management in `user.js` and `autoRemove.js`.
- Each file now has improved test cases for major endpoints, error scenarios, and edge cases, increasing overall coverage.
**Supplemental material:**
- Before: 
- After:
> Increase Test Coverage and Improve Error Handling in Server Files

- client/app/account/page.js
Enhancement of `Pantry` component with improved section loading and URL parameter handling.
This PR refines the `Pantry` component by adding a `Suspense` fallback for smoother section loading, improving URL parameter handling, and simplifying the `IngredientInput` render logic. This enhances user experience and maintains the component structure cleanly.
- Added a `Suspense` fallback specifically for section loading.
- Enhanced `useEffect` to set `activeSection` based on URL `section` query parameter.
- Removed an unnecessary fragment (`<>`) around `IngredientInput` for cleaner code.
- Ensure proper navigation and loading experience across all sections.
- Further testing for any edge cases related to URL-based navigation.
- Tested component loading via direct URL access with various …
> Enhance Account Page Navigation and Implement Suspense Loading Fallback

- client/app/favorite/favoriteInfo.js
- server/discover/autoRemove.js
**Issue / Feature:** Favorite Page + auto removal
**Description:** Made the use recipe functional in favorite and accounted for units in auto removal
**What's in this change?:** Changed the Use Recipe button so it works exactly the same way as in the recipe and discover pages. Added checks to ensure that units are converted when removing from pantry.
> fixed use recipe

- client/app/account/page.js
**Issue / Feature:**  
Revert recent frontend change.
**Description:**  
This PR reverts the latest frontend changes to restore the project to a previous stable state.
**What's in this change?:**  
Reverts unintended frontend modifications from the latest commit, keeping server-side changes intact.
**Whats left to do?:**  
Nothing
**Testing changes:**  
No new tests
> Reverted Client Changes

- client/app/discover/DiscoverPage.module.css
- client/app/discover/page.js
- client/app/recipe/RecipePage.module.css
#141 
Beginning to make the discover page responsive / similar to recipe page
Added breakpoints and css to main discover page
Changed formatting of page to match recipe page
Nothing
> Discover page responsive

- server/register.js
Bug - Registration
Fixing bug where there was a mismatch between inserts and expressions on backend
Adding back $9
> fixing register bug

- client/app/components/recipeDetail.js
Adds a feature allowing users to add missing ingredients directly from the `RecipeDetails` page to their database.
This PR introduces a button next to each missing ingredient on the `RecipeDetails` page. Users can click this button to directly add the ingredient to their personal ingredients database without leaving the recipe view. 
- A new button component next to each missing ingredient.
- An API call to add the ingredient to the user's database when the button is clicked.
- Upon successful addition, the ingredient is moved from the "Missing Ingredients" list to the "Used Ingredients" list in the UI.
- Updates localStorage to reflect changes in ingredient status.
- Additional testing to ensure ingredient status updates correctly in all components where ingredients are displayed.
- …
> Add a add button for adding ingredient directly from the recipe page

- client/app/recipe/recipe.js
- server/favoriteBackend/favorites.js
- server/tests/favorites.test.js
…e loads with proper favorited state
Removed alerts. The red heart now displays favorite state.
additional backend endpoint to fetch favorite recipe_id, toggle feature between states
N/A
No additional test
> Recipe page load favorited state

- server/email_noti/email.js
- server/email_noti/email.test.js
Styling email message
Make message body of email cleaner.
changes to body format
N/A
> style email message

- client/app/account/AllergenInput.js
- client/app/account/account.module.css
- client/app/register/regStep2.js
- client/app/register/regStep3.js
- client/app/register/register.module.css
- server/register.js
- server/tests/register.test.js
#149
#153
Adding ingredient and unit suggestion to registration similar to 'Account' for consistency
Add autosuggestions to allergies based on ingredients similar to auto-suggestions  "account" tab
regStep2.js - fetch ingredients from Spoonacular API and use the data for ingredient input auto-suggestions
regStep3.js - fetch ingredients from Spoonacular API and use the data for allergen input auto-suggestions
register.js - before inserting the ingredient, check if the ingredient exists in the ingredients table and insert the ingredient into 
ingredients table if it doesn't exist
allergenInput.js - fetch ingredients from Spoonacular API and use the data for allergen input auto-suggestions
**Testing …
> add ingredient/allergen autosuggestions

- client/app/components/recipeDetail.js
> fix minor bug causing user unable to import ingredient

- client/app/favorite/favoriteInfo.js
Correct ingredients styling.
compare user's ingredients with recipe ingredients if correct name, unit, and amount greater than recipe display black, red other wise.
logic changes, and clean up unwanted code.
N/A
Before:
After:
> FavoriteInfo Ingredients

- client/app/components/loading.js
> fixing casing

- client/app/components/recipeDetail.js
- server/ingredient/ingredient.js
**Issue / Feature:** Customization for add missing ingredient
**Description:** User can choose to add exact amount or custom amount of missing ingredients in the details page
**What's in this change?:** Changed how adding ingredient is handled
**Whats left to do?:** Styling changes
**Testing changes:** N/A
> editable add on recipe page

- client/app/components/recipeDetail.js
**Issue / Feature:** Add public access to discover recipe details
**Description:** Allow public viewing of recipe details while keeping ingredient highlighting/management for authenticated users
- Added authentication check in RecipeDetails component
- Modified IngredientsList for both auth/unauth views 
- Added conditional rendering for ingredient status and add buttons
- Implemented login redirect for "Cooked" button when unauthenticated
- Added user ingredients fetching for authenticated users
- Add loading states while fetching user ingredients
- Improve error handling
- Add visual feedback for ingredient actions
- Test recipe details loads without auth
- Verify ingredients show without highlighting when unauth
- …
> Add public access to discover recipe details and handle ingredients

- client/app/components/recipeDetail.js
- client/app/components/recipeDetail.module.css
Style update for modal option container
Updated the layout of the option container to make it horizontally centered and added spacing between the items inside the container.
- Changed the `.optionContainer` CSS to center the content horizontally and vertically using flexbox.
- Added spacing between elements inside the container using the `gap` property.
- Ensured the background is slightly transparent with full viewport coverage for better visibility.
**What's left to do?:**
- No additional changes are required unless further UI adjustments are needed.
- Verify that the option container is centered properly in the viewport.
- Ensure there is enough space between the options in the container.
- Test the …
> style change

- client/app/discover/DiscoverPage.module.css
- client/app/discover/page.js
Fix UI for shopping list/cart.
Instead of the appearing at button of screen, it now has a dropdown 
Ui  changes and some functionality changes such as removing item clears shoppingList so user can regenerate list.
N/A
N/A
> Shopping list UI

- server/tests/shoppingListTest.test.js
test case
jest test coverage code for functions in /discover/shoppingList
increase in test case coverage
N/A
discover/shoppingList
> shoppingList jest test

- client/app/account/IngredientInput.js
Fix negative quantity handling in pantry ingredients
Negative quantities were persisting in the pantry instead of being removed. Added validation and proper handling of zero/negative values.
**What's in this change:**
- Added quantity validation and prompts for removal when <= 0
- Set min="0" and step="0.01" on inputs
- Modified save logic to filter invalid quantities
- Improved error handling
**What's left to do:**
- Maybe a website specific pop-up instead of chrome notification
- No changes in testing as this is front-end
Before:
After:
> fixed negative ingredient bug

- client/app/components/recipeDetail.js
**Issue / Feature:** Progress bar in recipe details page
**Description:** The bar is reflective of the users goals now
**What's in this change?:** added a server side call to retrieve the goals and changed the values depicted in the tracker. Also fixed a bug where the units would not get added automatically in the pantry if the user chose to add the exact amount for an ingredient.
> progress bar in details page + bug fix for add exact amount

- client/app/discover/DiscoverPage.module.css
- client/app/discover/page.js
People couldn't tell what the checkbox is for, and list of ingredients before adjustment.
changed checkbox to shopping cart icon
change checkbox to shopping cart icon, and a display before ingredients before adjustments
N/A
N/A
> ShoppingList Feedback Improvements

- client/app/components/recipeDetail.js
**Issue / Feature:** Add all ingredients
**Description:** Added units to add all ingredients feature
**What's in this change?:** Added units to the dropdown for add all ingredients
> units for add all ingredients

- client/app/discover/page.js
…card
when shopping cart icon is pressed the recipe detail page displays
N/A
Fix gap between favorite button and shopping cart
N/A
> ShoppingCart page propagation

- client/app/account/NutritionHistory.js
- client/app/account/page.js
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
Added a Nutrition History feature to the application, allowing users to view their nutritional intake for a selected date in a bar graph.
This feature introduces a `NutritionHistory` component where users can:
- Select a date using a calendar widget.
- View their nutritional intake (e.g., protein, carbohydrates, fats, fiber, etc.) for the selected date.
- The data is displayed in an interactive bar graph.
1. `NutritionHistory` Component:
- Added a date picker (`react-datepicker`) for date selection.
- Integrated `react-chartjs-2` with a `Bar` chart to visualize nutrition data.
- Dummy data is being used currently, with placeholders for API integration.
2. New Dependencies:
- `react-datepicker`: For selecting a date.
- `chart.js` and `react-chartjs-2`: For rendering the bar graph.
3. …
> Nutrition History

- client/app/account/EditableField.js
- client/app/account/NutritionInput.js
- client/app/account/Settings.js
- client/app/account/Settings.module.css
- client/app/account/account.module.css
- client/app/components/addAndRemoveFavorites.js
- client/app/components/recipeDetail.js
- client/app/discover/DiscoverPage.module.css
- client/app/discover/page.js
#180 
- Mainly styling adjustments / fixes
- Adjusted styling on shopping cart
- Adjusted styling on account - nutrients tab
- Adjusted styling on account - settings tab
- Fixed button styling on recipe cards
Nothing
> Nutrition styling updates

- client/app/account/EditableField.js
- client/app/account/NutritionInput.js
- client/app/account/Settings.js
- client/app/account/Settings.module.css
- client/app/account/account.module.css
- client/app/components/addAndRemoveFavorites.js
- client/app/components/recipeDetail.js
- client/app/discover/DiscoverPage.module.css
- client/app/discover/page.js
Reverts csci-499-fa24/Team6#213
> Revert "Nutrition styling updates"

- client/app/components/FavoriteButton.module.css
- client/app/components/recipeDetail.js
- client/app/components/recipeDetail.module.css
Adding back nutrition updates within recipe detail and favorite button in recipe details
> adding back peoples changes

- client/app/components/recipeDetail.js
- client/app/components/recipeDetail.module.css
Moved the add all ingredient button to the header section
Nothing
> moving add button to ingredient header

- client/package-lock.json
- client/package.json
> package added

- client/app/account/NutritionHistory.js
- client/app/account/NutritionHistory.module.css
- client/app/recipe/RecipePage.module.css
- client/app/recipe/recipe.js
#249 
Updating nutrition tracker frontend
Changed buttons / inputs to match rest of the website
Added responsiveness to the page
Changed nutrition colors to match the colors on other pages
Refined layout
Nothing
> updating graph input frontend

- client/app/recipe/recipe.js
- package-lock.json
- server/package-lock.json
Issue / Feature: Search and filter functionality removal
Description: The previous version of the RecipePage component included a search bar and various filters for recipe types, cuisines, and diets. The updated version removes these features, focusing solely on displaying recommended recipes based on the user's pantry ingredients.
What's in this change?:
Removed the Filters component and all associated state variables and logic related to filtering and searching recipes.
Simplified the fetchRecipes method to only use the user's ingredients, without any additional filtering parameters.
Removed the search-related methods (handleSearchChange, handleSearchClick) and the search input field.
Kept the core recipe display functionality, including the recipe cards, pagination, and favorite recipe …
> Remove search and filter from recipe, not working
